### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6

### ISSUE THREAD

**Issue by ZhiangChen** [Open-UAV/openuav-turbovnc#18]
I installed open3d and have this issue when importing open3d
```
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/open3d/__init__.py", line 35, in <module>
    from .open3d import * # py2 py3 compatible
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/local/lib/python2.7/dist-packages/open3d/open3d.so)
```
I tried this, but it doesn't work: https://github.com/tensorflow/tfx/issues/331#issuecomment-511837564

**Comment by harishanand95** [comment]
Fixed in your session, seems unrelated to OpenUAV.

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test

sudo apt-get update

sudo apt-get install gcc-4.9

sudo apt-get upgrade libstdc++
```

After that you can check if you get GLIBCXX desired version like this:

`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`
